export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
export const GET_POKEMON_ID = "GET_POKEMON_ID";
export const FILTER_POKEMONS = "FILTER_POKEMONS";    
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const GET_ALL_TYPES = "GET_TYPES";
export const CREATE_POKEMON = "CREATE_POKEMON";
export const ORDER_BY_NAME ="ORDER_BY_NAME";
export const FILTER_TYPE = "FILTER_TYPE"
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN"

export const FILTER_BY_ATTACK = "FILTER_BY_ATTACK"

